### ISSUE TITLE
An oversight in mining.pwn

### ISSUE THREAD

**Issue by Daniel-Cortez** [zeelorenc/sf-cnr#64]
The following code from the `OnPlayerKeyStateChange()` hook in `mining.pwn` looks suspicious: https://github.com/zeelorenc/sf-cnr/blob/4a77e20146d7ca8e055d2a6c12ec5ccba212f254/gamemodes/irresistible/cnr/features/minijobs/mining.pwn#L286
Variables `X`, `Y`, and `Z` are used on this line, but they weren't assigned any coordinates before being used (zero-initialized by default), so the player is turned facing the point `(0.0, 0.0, 0.0)`.

You'll probably want to assign some coordinates to these variables, or just remove them completely.

**EDIT:** Also, judging from the function header in `helpers.pwn`
https://github.com/zeelorenc/sf-cnr/blob/4a77e20146d7ca8e055d2a6c12ec5ccba212f254/gamemodes/irresistible/helpers.pwn#L770
the 4'th argument is supposed to be an angle offset, not a Z coordinate.

**Comment by zeelorenc** [comment]
> I fixed it. try this.
> [zekodef@8910e83](https://github.com/zekodef/sf-cnr/commit/8910e8373648204ae76156dfa56d19385108b2a4)

Hi please create a pull request. And btw, offset is an optional parameter so you dont even need to put anything in the SetPlayerFacePoint offset parameter.
