### ISSUE TITLE
Another oversight in admin_three.pwn

### ISSUE THREAD

**Issue by Daniel-Cortez** [zeelorenc/sf-cnr#65]
https://github.com/zeelorenc/sf-cnr/blob/4a77e20146d7ca8e055d2a6c12ec5ccba212f254/gamemodes/irresistible/cnr/commands/admin/admin_three.pwn#L542-L543
Local variables `ban_date` and `ban_expire` are used before being assigned a value, which is suspicious.
It seems that function `cache_get_field_content_int` is used in an incorrect way; the 3'rd argument of this function should be a DB handle (it can be skipped though).
The code was probably supposed to be written in the following way:
```Pawn
ban_date = cache_get_field_content_int( row, "DATE" );
ban_expire = cache_get_field_content_int( row, "EXPIRE" );
```

**Comment by zeelorenc** [comment]
old code just left unconverted as the script is years old

make a pr to address this ... or ill do it soon

**Comment by ItsStev** [comment]
created pr to resolve this issue
