### ISSUE TITLE
Database query bug

### ISSUE THREAD

**Issue by zekodef** [zeelorenc/sf-cnr#79]
sfcnr.pwn
	// Truncate accounts older than 2 months
	mysql_function_query( dbHandle, "UPDATE USERS SET CASH=0,BANKMONEY=0,COINS=0.0,XP=0 WHERE UNIX_TIMESTAMP()-`LASTLOGGED`>5259487", true, "onRemoveInactiveRows", "d", 2 );
It query XP colum but XP colum is not found.

**Comment by ItsStev** [comment]
You haven't created the SQL tables correctly, XP field is in USERS table.

**Comment by zekodef** [comment]
Thank you

**Comment by zekodef** [comment]
I found it has been removed in 20190101_cnr_remove_xp_autosave.sql

**Comment by zekodef** [comment]
I fixed it by replace this
mysql_function_query( dbHandle, "UPDATE USERS SET CASH=0,BANKMONEY=0,COINS=0.0 WHERE UNIX_TIMESTAMP()-LASTLOGGED>5259487", true, "onRemoveInactiveRows", "d", 2 );
Thank you
