### ISSUE TITLE
missing plugins

### ISSUE THREAD

**Issue by AhmedMohamed264** [zeelorenc/sf-cnr#92]
Hello, i just wanted to mention 3 includes/plugins that their links are broken and i can't find them on google.
So here is the 3 includes/plugins:

- MathParser
- sampcac_server
- MerRandom

So if anybody got them, please leave the links for them.
Thanks!

**Comment by Livboeree** [comment]
have you found them buddy? i'm trying to run this gamemode but it seems to be impossible

**Comment by AhmedMohamed264** [comment]
Contact me on discord or Facebook so we can solve the problem.

Discord: Mr.Ahmed#9945

Facebook: https://www.facebook.com/medo.mohamed.264/
